import type { GetServerSideProps, NextPage } from 'next'
import Head from 'next/head'
import { useRouter } from 'next/router'
import React, { useEffect } from 'react'
import { ClientDTO } from '../src/api/base'
import { ClientsContainer } from '../src/clients/ClientsContainer'
import { ErrorBoundary } from '../src/components/ErrorBoundary/ErrroBoundaries'
import { useAuthConext, UserAuthState } from '../src/user/AuthContext'
import { AuthGuard } from '../src/user/AuthGuard'


interface MyFooterProps {
  companyName?: string
}

export const MyFooter = (props: MyFooterProps) => {
    return (
        <footer>
            Powered by {' '} {props.companyName ?? "Toptal"}
        </footer>
    )
}

const Home: NextPage<{ clients: ClientDTO[] | undefined}> = (props) => {
    return (
        <ErrorBoundary>
            <AuthGuard>
                <div>
                    <Head>
                        <title>Create Next App</title>
                        <meta name="description" content="Generated by create next app" />
                        <link rel="icon" href="/favicon.ico" />
                    </Head>

                    <main>
                        <h1>We will be back at 17:10</h1>
                        <h2>Form the server</h2>
                        {
                            props.clients?.map((client) => {
                                return (
                                    <div key={client.id}>
                                        {client.name}
                                    </div>
                                )
                            })
                        }

                        <h2>
                            From fetch after mount 
                        </h2>


                        <ClientsContainer />

                        {/* <Button variant="contained">Hello</Button> */}

                    </main>

                    {/* <MyFooter /> */}
                </div>
            </AuthGuard>
        </ErrorBoundary>
    )
}

export const getServerSideProps: GetServerSideProps = async (ctx) => {
    // const clients = await fetchClients()
    
    return {
        props: {
            clients: []
        }
    }
}

export default Home
